FROM jenkins/jenkins:lts

# Cambiar a usuario root para poder instalar paquetes del sistema
USER root

# Instalar el cliente/CLI de Docker y herramientas necesarias
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 2. Instalar el binario oficial de Trivy
RUN curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin