FROM jenkins/jenkins:lts

# Cambiar a usuario root para poder instalar paquetes del sistema
USER root

# Instalar el cliente/CLI de Docker y herramientas necesarias
RUN apt-get update && \
    apt-get install -y docker.io && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Volver al usuario jenkins por seguridad (opcional, pero buena práctica)
# USER jenkins