# ==========================================================
# Identificación del proyecto
# ==========================================================
sonar.projectKey=survey.form.micro.template
sonar.projectName=survey.form.micro.template
sonar.projectVersion=1.0.0

# ==========================================================
# Servidor SonarQube
# ==========================================================
sonar.host.url=http://18.117.100.66:9000
sonar.token=sqa_e497f5f5fb4c14e3517e4e2f6b57c2ed4df28ff6

# ==========================================================
# Código fuente y análisis
# ==========================================================
sonar.sources=src,index.js
sonar.tests=test

# Codificación de los archivos
sonar.sourceEncoding=UTF-8

# ==========================================================
# Cobertura de pruebas (Vitest -> lcov)
# ==========================================================
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# ==========================================================
# Exclusiones
# ==========================================================
# Fuera del análisis general
#sonar.exclusions=node_modules/**,coverage/**,schemas/**,**/*.routes.js,**/config.js,**/constants.js
sonar.exclusions=\
  node_modules/**,\
  coverage/**,\
  dist/**,\
  build/**,\
  src/schemas/**,\
  src/routes/**,\
  src/config/**,\
  src/dtos/**,\
  src/utils/constants.js

# Fuera del cálculo de cobertura (coherente con vitest.config.js)
#sonar.coverage.exclusions=index.js,src/**/*.routes.js,src/utils/config.js,src/utils/constants.js,test/**
sonar.coverage.exclusions=\
  index.js,\
  app.js,\
  src/schemas/**,\
  src/routes/**,\
  src/config/**,\
  src/dtos/**,\
  src/utils/constants.js,\
  test/**