# Identificación del proyecto (debe ser único en SonarQube)
sonar.projectKey=tigo-postgres-connector
sonar.projectName=@tigo/postgres-connector
sonar.projectVersion=0.0.53

# Configuración de la instancia remota
#sonar.host.url=https://sonarqube.tigo.net.bo
#sonar.login=squ_b551bb7d68538f10a0b2ab91198a554aa5fda6f1

# Ruta del código fuente y tests
sonar.sources=src
sonar.tests=test

# Encoding y lenguaje
sonar.language=js
sonar.sourceEncoding=UTF-8

# Excluir node_modules y otros archivos irrelevantes
sonar.exclusions=node_modules/**,**/*.spec.js

# Configuración de cobertura (usando c8/lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

##########################################################
############## Ejecucion ################
##########################################################
### Para limpiar si es necesario
# > rm -rf node_modules package-lock.json

### Instala las dependencias necesarias
# > npm install --verbose
# > npm run coverage

### Instala el scanner de SonarQube client
# > npm install -g sonarqube-scanner
# > sonar-scanner
# > sonar-scanner -Dsonar.login=squ_b551bb7d68538f10a0b2ab91198a554aa5fda6f1