export const errorCodes = {
  MISSING_REQUIRED_PARAMETER: "BR001",
  INVALID_DATA_TYPE: "BR002",
  UNSUPPORTED_FORMAT: "BR003",
  UNSUPPORTED_HTTP_METHOD: "BR004",
  INVALID_TOKEN: "AU001",
  TOKEN_EXPIRED: "AU002",
  MISSING_TOKEN: "AU003",
  PAYMENT_REQUIRED: "PM001",
  INSUFFICIENT_BALANCE: "PM002",
  PAYMENT_AUTHORIZATION_FAILED: "PM003",
  SUSCRIPTION_EXPIRED: "PM004",
  PAYMENT_TOKEN_INVALID: "PM005",
  ACCESS_DENIED: "FB001",
  NOT_FOUND: "NF001",
  MSISDN_NOT_FOUND: "NF002",
  METHOD_NOT_ALLOWED: "MA001",
  METHOD_NOT_IMPLEMENTED: "MA002",
  NOT_ACCEPTABLE: "NA001",
  UNSUPPORTED_MEDIA_TYPE: "NA002",
  RESOURCE_CONFLICT: "CF001",
  INVALID_DOCUMENT_FORMAT: "UE001",
  TOO_MANY_REQUESTS: "RL001",
  GENERIC_INTERNAL_SERVER_ERROR: "SE001",
  GATEWAY_OR_PROXY_ERROR: "BG001",
  SERVICE_TEMPORARILY_UNAVAILABLE: "SU001",
  TIMEOUT_WAITING_FOR_UPSTREAM_SERVICE: "GT001",
  VALIDATION: "BR002", // -> 400 Invalid data type
  CONFLICT: "CF001", // -> 409 Resource conflict
  UNKNOWN: "SE001", // -> 500 Generic internal server error
};

export const setError = (message, errorCode) => {
  const validationError = new Error(message);
  validationError.errorCode = errorCode;
  return validationError;
};
